refactor: apply clean architecture principles & prepare for rokon-qt
I did not want this to be a breaking change for packagers so I have kept rokon-gtk as the default compilation target. Additionally, the rokon binary no longer exists. It is now either rokon-gtk or rokon-qt. Considering the facts: The only package that had a opportunity to be used by bug testers was the RPM, it is the only one that actually obsoletes the 2024/12/16 16:00:03 main.go:73: Config directory: /home/romvnly/.config/rokon
2024/12/16 16:00:03 main.go:74: Cache directory: /home/romvnly/.cache/rokon
2024/12/16 16:00:03 main.go:75: Log file: /home/romvnly/.local/share/rokon/logs/latest.log
2024/12/16 16:00:03 main.go:76: Starting Rokon. Now with more telemetry!
2024/12/16 16:00:03 main.go:115: Version 1.0.0 commit  branch  (built on 2024-12-05)
2024/12/16 16:00:03 glib.go:33877: WARN Unknown key gtk-modules in /home/romvnly/.config/gtk-4.0/settings.ini priority=4 code_file=../gtk/gtksettings.c code_line=1708 code_func=gtk_settings_load_from_key_file glib_domain=Gtk
2024/12/16 16:00:03 cli.go:24: Usage:
  rokon [flags]
  rokon [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  config      Configure settings
  help        Help about any command
  version     Show version

Flags:
  -h, --help      help for rokon
  -v, --version   version for rokon

Use "rokon [command] --help" for more information about a command.

2024/12/16 16:00:03 glib.go:33877: ERROR g_application_set_flags: assertion '!application->priv->is_registered' failed glib_old_log_api=1 priority=4 glib_domain=GLib-GIO
2024/12/16 16:00:03 rokuDiscover.go:76: Interface: lo, Status: up, Type: loopback
2024/12/16 16:00:03 rokuDiscover.go:76: Interface: enp44s0, Status: up, Type: Ethernet
2024/12/16 16:00:03 rokuDiscover.go:76: Interface: wlp0s20f3, Status: up, Type: Wi-Fi
2024/12/16 16:00:03 rokuDiscover.go:76: Interface: tailscale0, Status: up, Type: Unknown
2024/12/16 16:00:03 glib.go:33877: ERROR ../gobject/gsignal.c:2426: signal 'activate' is invalid for instance '0x55f03d2a62c0' of type 'GMenuItem' glib_old_log_api=1 priority=4 glib_domain=GLib-GObject
2024/12/16 16:00:03 glib.go:33877: ERROR ../gobject/gsignal.c:2426: signal 'activate' is invalid for instance '0x55f03d2aae20' of type 'GMenuItem' glib_old_log_api=1 priority=4 glib_domain=GLib-GObject
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] llvmpipe (LLVM 19.1.5, 256 bits) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] Intel(R) UHD Graphics (TGL GT1) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] Intel(R) UHD Graphics (TGL GT1)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] llvmpipe (LLVM 19.1.5, 256 bits)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] llvmpipe (LLVM 19.1.5, 256 bits) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] Intel(R) UHD Graphics (TGL GT1) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] Intel(R) UHD Graphics (TGL GT1)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] llvmpipe (LLVM 19.1.5, 256 bits)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] llvmpipe (LLVM 19.1.5, 256 bits) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] Intel(R) UHD Graphics (TGL GT1) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] Intel(R) UHD Graphics (TGL GT1)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] llvmpipe (LLVM 19.1.5, 256 bits)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] llvmpipe (LLVM 19.1.5, 256 bits) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] Intel(R) UHD Graphics (TGL GT1) priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [0] NVIDIA GeForce RTX 3060 Laptop GPU   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [1] Intel(R) UHD Graphics (TGL GT1)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:            [2] llvmpipe (LLVM 19.1.5, 256 bits)   priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Removing driver /usr/lib64/libvulkan_radeon.so due to not having any physical devices priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Removing driver /usr/lib64/libvulkan_powervr_mesa.so due to not having any physical devices priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Removing driver /usr/lib64/libvulkan_panfrost.so due to not having any physical devices priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Removing driver /usr/lib64/libvulkan_nouveau.so due to not having any physical devices priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Removing driver /usr/lib64/libvulkan_intel_hasvk.so due to not having any physical devices priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Removing driver /usr/lib64/libvulkan_freedreno.so due to not having any physical devices priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Removing driver /usr/lib64/libvulkan_broadcom.so due to not having any physical devices priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: Failed to find vkGetDeviceProcAddr in layer "libVkLayer_MESA_device_select.so" priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message: vkCreateDevice layer callstack setup to: priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:    <Application> priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      || priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:    <Loader> priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:      || priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:    <Device> priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:04 glib.go:33877: INFO Vulkan: Loader Message:        Using "Intel(R) UHD Graphics (TGL GT1)" with driver: "/usr/lib64/libvulkan_intel.so" priority=6 code_file=../gdk/gdkvulkancontext.c code_line=1703 code_func=gdk_vulkan_debug_report glib_domain=Gdk
2024/12/16 16:00:05 gui.go:42: Discovered Rokus: [{roku:ecp uuid:roku:ecp:X00000GU4LA3 http://10.0.0.219:8060/ Roku/14.0.4 UPnP/1.0 Roku/14.0.4 map[Cache-Control:[max-age=3600] Device-Group.roku.com:[0E329AE3435A606DA090] Ext:[] Location:[http://10.0.0.219:8060/] Server:[Roku/14.0.4 UPnP/1.0 Roku/14.0.4] St:[roku:ecp] Usn:[uuid:roku:ecp:X00000GU4LA3] Wakeup:[MAC=00:bf:af:91:04:9e;Timeout=10]] <nil>}]
2024/12/16 16:00:05 gui.go:31: Body: <?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:roku-com:device:player:1-0</deviceType>
<friendlyName>Kelis’s Roku Tv</friendlyName>
<manufacturer>TCL</manufacturer>
<manufacturerURL>support.tcl.com/us</manufacturerURL>
<modelDescription>Roku Streaming Player Network Media</modelDescription>
<modelName>C177X</modelName>
<modelNumber>C177X</modelNumber>
<modelURL>http://www.roku.com/</modelURL>
<serialNumber>X00000GU4LA3</serialNumber>
<UDN>uuid:28000000-0000-1000-8000-00bfaf91049e</UDN>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>360</width>
<height>219</height>
<depth>8</depth>
<url>device-image.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:roku-com:service:ecp:1</serviceType>
<serviceId>urn:roku-com:serviceId:ecp1-0</serviceId>
<controlURL></controlURL>
<eventSubURL></eventSubURL>
<SCPDURL>ecp_SCPD.xml</SCPDURL>
</service>
<service>
<serviceType>urn:dial-multiscreen-org:service:dial:1</serviceType>
<serviceId>urn:dial-multiscreen-org:serviceId:dial1-0</serviceId>
<controlURL></controlURL>
<eventSubURL></eventSubURL>
<SCPDURL>dial_SCPD.xml</SCPDURL>
</service>
</serviceList>
</device>
</root> package.

The Flathub and Snapcraft packages need to be investigated more. It'd be a shame to not provide a version for both.